VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "master"
  config.vm.synced_folder "shared", "/home/vagrant/projects"
  config.vm.provision "shell", path: "config-ansible.sh"
  config.vm.network "private_network", ip: "192.168.50.1"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "master"
    vb.memory = "768"
    vb.cpus = "1"
  end
end
